### PR TITLE
fix battery level not updating

### LINKED ISSUE #114: ESP32-BLE-Gamepad sending/update battery level
Guys, I need help, I'm new to this business, help me implement in my code, a part of the code for reading the battery level, so that win10 displays the level in BT devices, let it work even if you need to reconnect the device to get up-to-date information about battery level

[WirelessGameHub.txt](https://github.com/lemmingDev/ESP32-BLE-Gamepad/files/9083629/WirelessGameHub.txt)

### PR DESCRIPTION
**Pull request by spleen1981**
Needs https://github.com/h2zero/NimBLE-Arduino/commit/f699ab8395c3caf895c5d2a8ff82bf48e3442d32 at least.
Fixes #114 and #85

### CODE REVIEW

**Comment by Xstasy** [comment]
I tested this, and unfortunately it does not update battery level on Windows 11 at least. Need to call begin() for it to update / or reconnect.

**Comment by spleen1981** [comment]
@Xstasy can you share your code.
You should call `BleGamepad::setBatteryLevel(uint8_t level)` for each update anyways.

**Comment by lemmingDev** [comment]
Thanks @spleen1981

**Comment by lemmingDev** [comment]
I will look at issues #110 and #116 over the next few days and then release a new version with this battery fix (unless you want to check them out yourself ;) )

**Comment by spleen1981** [comment]
> I will look at issues #110 and #116 over the next few days and then release a new version with this battery fix (unless you want to check them out yourself ;) )

Had a solution handy for #110, see #118.
#116 looks just needs a deep dive in the report structure and relevant documentation...

**Comment by APiRacing** [comment]
> > Я рассмотрю проблемы [# 110](https://github.com/lemmingDev/ESP32-BLE-Gamepad/issues/110) и [# 116](https://github.com/lemmingDev/ESP32-BLE-Gamepad/issues/116) в течение следующих нескольких дней, а затем выпущу новую версию с этим исправлением батареи (если вы не хотите проверить их самостоятельно ;))
> 
> Было удобное решение для [# 110](https://github.com/lemmingDev/ESP32-BLE-Gamepad/issues/110), см. [# 118](https://github.com/lemmingDev/ESP32-BLE-Gamepad/pull/118). [# 116](https://github.com/lemmingDev/ESP32-BLE-Gamepad/issues/116) looks просто нуждается в глубоком погружении в структуру отчета и соответствующую документацию...

Can I contact you personally in some messenger?

**Comment by APiRacing** [comment]
> I tested this, and unfortunately it does not update battery level on Windows 11 at least. Need to call begin() for it to update / or reconnect.

Can I contact you personally in some messenger?

**Comment by APiRacing** [comment]
> I tested this, and unfortunately it does not update battery level on Windows 11 at least. Need to call begin() for it to update / or reconnect.

Can I contact you personally in some messenger?

**Comment by thakkaryash21** [comment]
@spleen1981 Hey I was trying this functionality out but unfortunately, the battery level does not update on Windows 11. I am settings the battery level using `BleGamepad::setBatteryLevel(uint8_t level)`. Could you please tell me what I can do to fix this?

**Pull request merged**
