### PR TITLE
Add Output Report Function

### PR DESCRIPTION
**Pull request by Sab1e-GitHub**
Added Output Report function and provided examples.
图片

### CODE REVIEW

**Comment by LeeNX** [comment]
Very nice @Sab1e-GitHub, thanks for the PR and pretty clean idea. I really like it. I wonder if improving the name from just ```enableOutputReport``` but to ```enableOutputVendorDefinedReport```, as I am going to use your base to possible enabled PlayerLED indicators and possible LightBar function.  
  
Another idea, can you write up a way that you can use the ```OutputReport```, either python or command script or something else? Move people would use this feature, but I am thinking would be great to get into SDL or Linux BlueZ support.

**Comment by Sab1e-GitHub** [comment]
Thank you very much for your recognition! Of course, you can modify the variable to enableOutputVendorDefinedReport.

Unfortunately, I am not familiar with SDL or Linux BlueZ, my apologies!

Additionally, I only have a C# test program. Would you need it?

**Comment by LeeNX** [comment]
Hey @lemmingDev, what do you think of the PR?  
  
@Sab1e-GitHub adding the link to the C# example in the  ```TestReceivingOutputReport.ino``` would be useful.  Let me see if I can come up with a more general/portable example, so that as many people can test as possible.

**Comment by Sab1e-GitHub** [comment]
@LeeNX I think you're right. I have added a link to the demo program in the `TestReceivingOutputReport.ino` file. Thank you very much for your suggestion!
@lemmingDev I hope you can accept this pr, it will be very helpful for others!

**Review by lemmingDev — APPROVED** [review]
Well done!

**Pull request merged**
