### PR TITLE
Fix circular dependacies, reboot issue and hid report descriptor for special buttons

### PR DESCRIPTION
**Pull request by dexterdy**
This merge request is essentially a collection of bugfixes for my previous pull request.

### CODE REVIEW

**Comment by lemmingDev** [comment]
Thanks. Did a few quick tests and seems to work fine

Not sure whether the start and select buttons should be enabled by default. What are your thoughts?

**Comment by lemmingDev** [comment]
Added configurable VID and PID values and have now released v4.0

Thanks for your help

**Comment by dexterdy** [comment]
Most controllers have them, so I'd say that it makes sense. But if you think otherwise, you can change that if you want

**Comment by lemmingDev** [comment]
Most controllers have buttons labelled as start/select, but I wonder how many have them set to that in the HID descriptor...
________________________________

**Comment by dexterdy** [comment]
Hm that I do not know. I just thought it would make sense. You're free to remove it, tho. I honestly didn't put much thought into it tho

**Pull request merged**
