### PR TITLE
Fix compatibility with NimBle version 2.0.0

### PR DESCRIPTION
**Pull request by Sab1e-GitHub**
The 2.0.0 version of NimBLE has modified some method signatures, we need to update these signatures in order for callbacks to work properly.

### CODE REVIEW

**Review by lemmingDev — APPROVED** [review]
Thanks!

I was hoping someone would submit a pull request for this

**Comment by Sab1e-GitHub** [comment]
I referred to this: https://github.com/h2zero/NimBLE-Arduino/blob/e78ede5e3a6613e15cff54ed138e5fecec359209/examples/NimBLE_Server/NimBLE_Server.ino#L17. It compiles correctly on my computer, and I have already tested that it runs properly.

**Comment by lemmingDev** [comment]
Would you mind checking again with latest masters of both?

**Comment by Sab1e-GitHub** [comment]
Do you mean that you need me to provide the link to version 2.0.0 of the NimBLE library? I noticed that the 2.0.0 release of the NimBLE library is not available on GitHub, but I can download version 2.0.0 from the Arduino IDE Library Manager.
Here is a screenshot:
图片

**Pull request merged**
