### PR TITLE
added support for a few special buttons

### PR DESCRIPTION
**Pull request by dexterdy**
This adds support for these optional hid buttons:

start
select
menu
home
back
volume increase
volume decrease
volume mute

This supersedes by previous pull request, because this code also adds support for start and select

### CODE REVIEW

**Comment by lemmingDev** [comment]
Looks like you're making some great progress.

Much appreciated

Let me know when you get to a state where your new configuration options are finished (will you include device ID changing?) and I'll test and merge changes

**Comment by dexterdy** [comment]
@lemmingDev 
Alright, I will do!
I will close the pull request in that case.

**Comment by lemmingDev** [comment]
Hi.

Which pull request would you like me to test and merge? 
They seem to be deleted.

**Comment by dexterdy** [comment]
hey there @lemmingDev! I have opened a new pull request with all the changed i have made. I am new to open source and git in general, so If i did something wrong, please do tell me

**Pull request closed without merging**
